#!/usr/bin/env bash
# A bash script that prints information about subdomains.
function get_sub_info {
  local domain=$1
  local subdomain=$2
  local full_domain="${subdomain}.${domain}"
  
  # Get record type and IP address
  local record_info=$(dig +short ${full_domain})
  
  if [[ -z "$record_info" ]]; then
    echo "No record found for ${full_domain}"
  else
    echo "The subdomain ${subdomain} is an A record and points to ${record_info}"
  fi
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  for sub in www lb-01 web-01 web-02; do
    get_sub_info $domain $sub
  done
else
  get_sub_info $domain $subdomain
fi
